#name: Dev to Prod

name: Deploy to Development

on:
  push:
    branches: [main]

jobs:
  Build_and_Push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.image}}

    steps:
      - uses: actions/checkout@v4

      - name: Login into Digital Ocean
        uses: docker/login-action@v3
        with:
          registry: registry.digitalOcean.com
          username: ${{ secrets.DIGITALOCEAN_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Assign version
        id: version_cal
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          fetch-depth: 0

      - name: Set Image Name
        id: image
        run: |
          IMAGE="${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ steps.version_cal.outputs.version_tag }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
        
      - name: Build and Push Docker image
        run: |
          
          echo "Bulding and Push image to Digital Ocean"

          docker build -t ${{ steps.image.outputs.image}} .
          docker push ${{ steps.image.outputs.image}}

  Deploy_Development:
    name: Deploy Development
    runs-on: ubuntu-latest
    needs: Build_and_Push
    steps:

      - name: Login into Digital Ocean
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}

        
      - name: Fetch Image and deploy to Dev
        id: docker_step
        run: |
          
          IMAGE="${{ needs.Build_and_Push.outputs.image }}"

          echo "Pull Docker image from DO"
          docker pull $IMAGE

          echo "deploying to Development"
          docker rm -f myapp || true
          docker run -d --name myapp -p 8080:8080 $IMAGE

      - name: Success Message
        if: steps.docker_step.outcome == 'success'
        run: echo "Application deployed Successfully!"

          




      
        
        



#'tags': ['latest', '1.0.270']
#'tags': ['Prod', '1.0.270']

#   tagging:
#     runs-on: ubuntu-latest
#     needs: development
#     steps:
#       - name: Checkout Code
#         uses: actions@checkout@v4

#       - name: Prod Version Tagging
#         id: version_cal
#         uses: paulhatch/semantic-version@5.4.0
#         with:
#           tag_prefix: "Prod-v"

#       - name: Login into Digial Ocean Registry
#         uses: docker/login-action@v3
#         with:
#           registry: registry.digitalocean.com
#           username: ${{ secrets.DIGITALOCEAN_TOKEN }}
#           password: ${{ secrets.DIGITALOCEAN_TOKEN }}

#       - name: Pull, Retag and Push Image
#         run: |

#           SOURCE_IMAGE="${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest"
#           TARGET_IMAGE="${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ steps.version_cal.outputs.version_tag }}"

#           echo "Pulling image from $SOURCE_IMAGE"
#           docker pull $SOURCE_IMAGE

#           echo "Retagging the image"
#           docker tag $SOURCE_IMAGE $TARGET_IMAGE







  